### PR TITLE
Fix conditional delete

### LINKED ISSUE #295: Link widget: don't add duplicate items following a message to the user that "following items are duplicate and won't be added".

### LINKED ISSUE #296: Link widget: remove clear button in Widget selection

### LINKED ISSUE #297: Link widget: gray out parent labels in the tree to indicate that they won't be selected.

### LINKED ISSUE #299: Remove "type" field when linking widgets when there is no options.

### LINKED ISSUE #302: Remove condition if the widget is removed

### PR DESCRIPTION
**Pull request by AdityaKhatri**
Fixes #295  
Fixes #299 
Fixes #302 
Fixes #296 
Fixes #297

Need to merge: https://github.com/toggle-corp/react-store/pull/382
https://github.com/toggle-corp/react-store/pull/393

### CODE REVIEW

File: src/widgetComponents/GeoLink/index.js [hunk 1]
```diff
@@ -60,31 +86,121 @@ export default class GeoLink extends React.PureComponent {
...
-                showLabel={false}
-                hideList
-                hideInput
-            />
+            <React.Fragment>
+                <GeoInput
+                    className={modalClassNames.join(' ')}
+                    geoOptionsByRegion={geoOptions}
+                    label={label}
+                    value={emptyArray}
```
Comment (tnagorra) [inline src/widgetComponents/GeoLink/index.js]: we can just leave the value to be undefined

File: src/widgets/edit/Matrix1d/RowContent/index.js [hunk 2]
```diff
@@ -48,50 +48,19 @@ export default class RowContent extends React.PureComponent {
...
-        this.setState({
-            showLinkModal: false,
-        }, () => this.props.onNestedModalChange(false));
-
-        return [
-            ...items,
-            ...newListOfItems,
-        ];
-    };
+    rowsModifier = rows => rows.map(r => ({
```
Comment (tnagorra) [inline src/widgets/edit/Matrix1d/RowContent/index.js]: This method must be static, also memoize wouldn't be so bad

File: src/widgets/edit/Matrix1d/index.js [hunk 3]
```diff
@@ -165,37 +173,15 @@ export default class Matrix1dEditWidget extends React.PureComponent {
...
-    }
-
-    handleAddFromWidgetClick = () => {
-        this.setState({ showLinkModal: true });
-    }
-
-    handleNestedModalChange = (showNestedLinkModal) => {
-        this.setState({ showNestedLinkModal });
-    }
+    rowsModifier = rows => rows.map(r => ({
```
Comment (tnagorra) [inline src/widgets/edit/Matrix1d/index.js]: This method must be static, also memoize wouldn't be so bad

File: src/widgets/edit/Matrix2d/DimensionContent/index.js [hunk 4]
```diff
@@ -49,46 +49,15 @@ export default class DimensionContent extends React.PureComponent {
...
-        this.setState({
-            showLinkModal: false,
-        }, () => this.props.onNestedModalChange(false));
-
-        return [
-            ...items,
-            ...newListOfItems,
-        ];
-    };
+    rowsModifier = rows => rows.map(r => ({
```
Comment (tnagorra) [inline src/widgets/edit/Matrix2d/DimensionContent/index.js]: This method must be static, also memoize wouldn't be so bad

File: src/widgets/edit/Matrix2d/SectorContent/index.js [hunk 5]
```diff
@@ -48,46 +48,15 @@ export default class SectorContent extends React.PureComponent {
...
-        this.setState({
-            showLinkModal: false,
-        }, () => this.props.onNestedModalChange(false));
-
-        return [
-            ...items,
-            ...newListOfItems,
-        ];
-    };
+    rowsModifier = rows => rows.map(r => ({
```
Comment (tnagorra) [inline src/widgets/edit/Matrix2d/SectorContent/index.js]: This method must be static, also memoize wouldn't be so bad

File: src/widgets/edit/Matrix2d/index.js [hunk 6]
```diff
@@ -338,37 +355,24 @@ export default class Matrix2dEditWidget extends React.PureComponent {
...
-    }
-
-    handleAddFromWidgetClick = () => {
-        this.setState({ showLinkModal: true });
-    }
-
-    handleNestedModalChange = (showNestedLinkModal) => {
-        this.setState({ showNestedLinkModal });
-    }
+    dimensionDataModifier = row => row.map(r => ({
```
Comment (tnagorra) [inline src/widgets/edit/Matrix2d/index.js]: This method must be static, also memoize wouldn't be so bad

File: src/widgets/edit/Matrix2d/index.js [hunk 7]
```diff
@@ -338,37 +355,24 @@ export default class Matrix2dEditWidget extends React.PureComponent {
...
+        id: randomString(16),
+        title: r.label,
+        originalWidget: r.originalWidget,
+        originalKey: r.originalKey,
+        color: undefined,
+        tooltip: '',
+        subdimensions: [],
+    }));
+
+    sectorDataModifier = row => row.map(r => ({
```
Comment (tnagorra) [inline src/widgets/edit/Matrix2d/index.js]: This method must be static, also memoize wouldn't be so bad

**Comment by tnagorra** [comment]
- Editing a widget inside conditional and pressing Cancel/Save will leave a grayed out screen.
- Adding a sub-dimension on Matrix2d will clear the dimension selected.
