### PR TITLE
Fix link widget modal

### LINKED ISSUE #354: Change select input to a list on side (Link widget)

### LINKED ISSUE #360: Wider multiselect in conditions edit

### LINKED ISSUE #364: Fix adding behavior in user/user groups

### LINKED ISSUE #366: Fix loading animation / no items display in discover projects/leads/entries/users

### PR DESCRIPTION
**Pull request by AdityaKhatri**
Fix #364 
Fix #360 
Fix #354 
Fix #366

### CODE REVIEW

File: src/views/DiscoverProjects/index.js [hunk 1]
```diff
@@ -442,17 +442,20 @@ export default class DiscoverProjects extends React.PureComponent {
...
-                            dataModifier={this.dataModifier}
-                            headerModifier={this.headerModifier}
-                            onHeaderClick={this.handleTableHeaderClick}
-                            keySelector={projectKeyExtractor}
-                            className={styles.projectsTable}
-                            emptyComponent={this.renderEmpty}
-                        />
-                        { pending && <LoadingAnimation large /> }
+                        { pending ? (
+                            <LoadingAnimation large />
```
Comment (tnagorra) [inline src/views/DiscoverProjects/index.js]: There is no "large" prop in LoadingAnimation

File: src/views/Leads/index.js [hunk 2]
```diff
@@ -595,17 +595,20 @@ export default class Leads extends React.PureComponent {
...
-                            headerModifier={this.headerModifier}
-                            headers={this.headers}
-                            onHeaderClick={this.handleTableHeaderClick}
-                            keySelector={Leads.leadKeyExtractor}
-                            className={styles.leadsTable}
-                            emptyComponent={this.renderEmpty}
-                        />
-                        { loadingLeads && <LoadingAnimation large /> }
+                        { loadingLeads ? (
+                            <LoadingAnimation large />
```
Comment (tnagorra) [inline src/views/Leads/index.js]: There is no large prop in LoadingAnimation

File: src/widgetComponents/LinkWidgetModal/index.js [hunk 3]
```diff
@@ -233,8 +309,13 @@ export default class LinkWidgetModal extends React.PureComponent {
...
         );
 
+        const selectedWidgetTitle = LinkWidgetModal.getTitleOfSelectedWidget(
+            selectedWidget,
+            this.filteredWidgets,
+        );
+
         const modalTitle = _ts('widgets.editor.link', 'modalTitle');
-        const widgetSelectionLabel = _ts('widgets.editor.link', 'widgetSelectionLabel');
+        // const widgetSelectionLabel = _ts('widgets.editor.link', 'widgetSelectionLabel');
```
Comment (tnagorra) [inline src/widgetComponents/LinkWidgetModal/index.js]: if not used, should remove _ts

File: src/views/DiscoverProjects/index.js (hunk 1 above)
Comment (tnagorra) [reply src/views/DiscoverProjects/index.js]: Do not unmount when loading, instead change the emptyComponent dynamically

File: src/views/Leads/index.js (hunk 2 above)
Comment (tnagorra) [reply src/views/Leads/index.js]: Do not unmount when loading, instead change the emptyComponent dynamically
